name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm ci
      - run: npm run build
      - run: npm run lint

      - run: npm ci
        name: "[API] Install dependencies"
        working-directory: api
      - run: npm run lint
        name: "[API] Lint"
        working-directory: api
      - run: npm run build
        name: "[API] Build"
        working-directory: api

      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
